@startuml
skinparam useBetaStyle true
skinparam componentStyle uml2

'not working yet but hopefully soon
<style>
    componentDiagram {
        LineColor #000

        component {
            LineColor #000
        }
    }
</style>

component LCARSWM #5cd

component POSIX

package "XLib" as XLibPackage {
    component XLib
    component XRandr
    component XPM
    component KeySym
}

actor User

User ..> XLib : open & close\nprogram windows
User ..> XRandr : change monitor\nadjust screens

User .left.> LCARSWM : Window & WM commands

LCARSWM ..> POSIX : read settings\nwrite log\nexecute programs\nread environment variables\nget time

LCARSWM ..> XRandr : handle monitor &\nscreen changes
LCARSWM ..> XLib : get events\nmanage windows
LCARSWM ..> XPM : load\ngraphics
LCARSWM ..> KeySym : keybinding\nhandling

@enduml