# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:8.0.292

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # install dependencies
      - run: sudo apt-get update
      - run: sudo apt-get install -y openjdk-8-jdk-headless libx11-dev libxpm-dev libxrandr-dev libpango1.0-dev libicu-dev libxml2-dev libtinfo5

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      - run: gradle build

      # run tests! https://youtrack.jetbrains.com/issue/KT-32608
      - run: gradle nativeTest

      - store_test_results:
          path: build/test-results

      - persist_to_workspace:
          root: ~/repo
          paths:
            - build/*

  deploy_aur:
    docker:
      - image: atennert/archlinux-cci-aur:0.0.1
        auth:
          username: atennert
          password: $DOCKERHUB_PASSWORD

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - 78:cd:db:a2:c1:cb:65:7a:16:75:b9:ec:08:7b:62:c3

      - attach_workspace:
          at: ~/repo

      - run: |
          if [[ -f "build/processedResources/native/main/etc/lcarsde/autostart" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

      - run: pwd

      - run: echo "aur.archlinux.org,2a01:4f9:c010:50::1 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLMiLrP8pVi5BFX2i3vepSUnpedeiewE5XptnUnau+ZoeUOPkpoCgZZuYfpaIQfhhJJI5qgnjJmr4hyJbe/zxow=" >> ~/.ssh/known_hosts

      # get deployment files for lcarswm
      - run: git clone ssh://aur@aur.archlinux.org/lcarswm.git

      # log the current contents
      - run: cat lcarswm/PKGBUILD
      - run: cat lcarswm/.SRCINFO

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy_aur:
          requires:
            - test
