# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:8.0.292

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # install dependencies
      - run: sudo apt-get update
      - run: sudo apt-get install -y libx11-dev libxpm-dev libxrandr-dev libpango1.0-dev libicu-dev libxml2-dev libtinfo5

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      # run tests! https://youtrack.jetbrains.com/issue/KT-32608
      - run: gradle nativeTest

      - store_test_results:
          path: build/test-results

  deploy_aur:
    docker:
      - image: atennert/archlinux-cci-aur:0.0.3
        auth:
          username: atennert
          password: $DOCKERHUB_PASSWORD

    steps:
      - add_ssh_keys:
          fingerprints:
            - 78:cd:db:a2:c1:cb:65:7a:16:75:b9:ec:08:7b:62:c3

      # get deployment files for lcarswm
      - run: git clone ssh://aur@aur.archlinux.org/lcarswm.git

      # log the current contents
      - run: cat lcarswm/PKGBUILD
      - run: cat lcarswm/.SRCINFO

      # update content
      - run: cd lcarswm && sed -i -e "s/^pkgver=[0-9\.]*$/pkgver=$CIRCLE_TAG/" PKGBUILD
      - run: cd lcarswm && updpkgsums
      - run: cd lcarswm && makepkg --printsrcinfo > .SRCINFO

      # log the new contents
      - run: cat lcarswm/PKGBUILD
      - run: cat lcarswm/.SRCINFO

      # upload new contents
      - run: cd lcarswm && git add -u && git commit -m "update to version $CIRCLE_TAG" && git push

  deploy_ubuntu:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo

    steps:
      - checkout

      # install dependencies
      - run: sudo apt-get update
      - run: sudo apt-get install -y default-jdk-headless devscripts debhelper fakeroot libx11-dev libxpm-dev libxrandr-dev libpango1.0-dev libicu-dev libxml2-dev libtinfo5

      - run: ./deploy-deb.sh

      - store_artifacts:
          path: ~/repo/build/deb/deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy_aur:
          context:
            - lcarsde-context
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - deploy_ubuntu:
          context:
            - lcarsde-context
          requires:
            - test
