package de.atennert.lcarswm.atom

/**
 * Contains enum values for all used X atoms. Only exception is WM_S*
 */
enum class Atoms(val atomName: String) {
    WINDOW("WINDOW"),
    ATOM("ATOM"),
    STRING("STRING"),
    UTF_STRING("UTF8_STRING"),
    MANAGER("MANAGER"),
    COMPOUND_TEXT("COMPOUND_TEXT"),

    WM_DELETE_WINDOW("WM_DELETE_WINDOW"),
    WM_PROTOCOLS("WM_PROTOCOLS"),
    WM_STATE("WM_STATE"),
    WM_CHANGE_STATE("WM_CHANGE_STATE"),
    WM_CLASS("WM_CLASS"),
    WM_NAME("WM_NAME"),

    NET_WM_NAME("_NET_WM_NAME"),
    NET_SUPPORTED("_NET_SUPPORTED"),
    NET_SUPPORTING_WM_CHECK("_NET_SUPPORTING_WM_CHECK"),
    NET_WM_DESKTOP("_NET_WM_DESKTOP"),
    NET_WM_STATE("_NET_WM_STATE"),
    NET_CLOSE_WINDOW("_NET_CLOSE_WINDOW"),
    NET_ACTIVE_WINDOW("_NET_ACTIVE_WINDOW"),
    NET_WM_MOVERESIZE("_NET_WM_MOVERESIZE"),
    NET_MOVERESIZE_WINDOW("_NET_MOVERESIZE_WINDOW"),
    NET_RESTACK_WINDOW("_NET_RESTACK_WINDOW"),

    LCARSWM_APP_MENU("LCARSWM_APP_MENU"),
    LCARSWM_STATUS_BAR("LCARSWM_STATUS_BAR")
}